### ISSUE TITLE
Composer Lint

### ISSUE THREAD

**Issue by RobLoach** [alairock/Composer-AtomEditor#1]
Use `composer validate`

**Comment by zimme** [comment]
Are you asking for the command `composer validate` or a linter which lint the file in the editor like with the linter packages?

**Comment by RobLoach** [comment]
Have the ability to run [`composer validate`](https://getcomposer.org/doc/03-cli.md#validate) to validate the project's `composer.json` file. :wink: 

Requiring a different linting method seems out of scope for this project, am I correct?

**Comment by zimme** [comment]
Then this should be available with version `v0.4.1`, and yes, in-line linting like with the linter plugins is a bit out of the scope of this project.
