### ISSUE TITLE
You are running composer with xdebug enabled. 

### ISSUE THREAD

**Issue by karneaud** [alairock/Composer-AtomEditor#12]
I got the subject error every time I run **composer in Atom**. This does not happen when I run it in **Terminal**. 

I also have problems with php as i recently upgraded to 5.6 yet composer seems to use the 5.3 version still on machine. 

I do not have this problem when using it in Terminal. 

I tried setting default composer path but sill does not work as expected.

Can you advise me on what can be done?

**Comment by zimme** [comment]
I'm out traveling until late april, don't know when I'll have the time to check this out. Have you tried removing the addon and then do a clean install of php and composer, such as everything works as expected, then reinstalling the atom addon again and see if that helps.

**Comment by karneaud** [comment]
Apparently starting Atom form the CLI as opposed to using the application's icon yielded different results.
