### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by tiagocaus** [alairock/Composer-AtomEditor#14]
What do I have to put in these fields on Atom?

I use linux and windows.

I have PHP installed on both operating systems.

<a href="http://i.imgur.com/KFroq5c.png">
  <img src="http://imgur.com/KFroq5cl.png" />
</a>

**Comment by zimme** [comment]
If `composer` is in your `PATH` environment variable you shouldn't need to put anything in the settings.

If you have `composer` installed somewhere unusual and not in your `PATH` then you need to specify the path in the settings.
