### ISSUE TITLE
Composer does not run

### ISSUE THREAD

**Issue by LukeMauldin** [alairock/Composer-AtomEditor#2]
When I execute any of the composer commands, I receive a message bar at the bottom saying "Complete".  I am in a directory that has a composer.json file at the root.  I have opened the composer.json file and I receive the same results when running any composer commands with that file open.  Composer runs correctly from the command line.  My composer is installed in /usr/local/bin/composer and I updated the path in the Settings to be sure it is correct.  When I look at the debug log I see this:
  [InvalidArgumentException]  
  Command "update -d /Users/lmauldin/dev/vmware/ubuntu_pe_dev/dev/pe/apps/ngt" is not defined.

**Comment by jasonmccallister** [comment]
I'm also getting the same issue, hopefully there is an update soon.

**Comment by zimme** [comment]
This should be fixed with version `v0.4.1`, please confirm and close the issue.

**Comment by jasonmccallister** [comment]
Worked for me, thanks!
