### ISSUE TITLE
Made a rewrite

### ISSUE THREAD

**Issue by zimme** [alairock/Composer-AtomEditor#4]
Hi

Made a rewrite of based on this package that works with the latest version of atom.

[atom-composer](/zimme/atom-composer)

**Comment by zimme** [comment]
@alairock So would you consider giving me the `composer` namespace on atom.io?

**Comment by alairock** [comment]
@zimme I added you to this project. Feel free to take ownership of this project. I haven't decided if I will fully release the namespace, but if I do, it will be to someone who is actively contributing to the repository.

**Comment by zimme** [comment]
Nice, will I be able to publish a new package version if I commit the rewrite to this repo or do I need some publication permissions on atom package server or something like that?

**Comment by alairock** [comment]
You should be able to. Let me know if you run into any issues.
