### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [alairock/Composer-AtomEditor#8]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.3.1`) of this package:
1. Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `<pack-name>` package
2. The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
3. Use a config schema instead. See the configuration section of https://atom.io/docs/latest/hacking-atom-package-word-count and https://atom.io/docs/api/latest/Config for more details
4. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
5. Requiring `View` from `atom` is no longer supported. Please require `atom-space-pen-views` instead: `{View} = require 'atom-space-pen-views'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by zimme** [comment]
I'll be merging #7 which is a re-write of the plugin, which should work and solve all the deprecation notices too. I have haft the day tomorrow allocated to this.

**Comment by zimme** [comment]
Should be fixed with version `v0.4.1`

**Comment by purplespider** [comment]
Atom 1.0.11 reports that only v0.3.1 is supported:
![](http://spdr.me/1lNS6+)

But it doesn't work as it has the deprications.

**Comment by zimme** [comment]
It has to do with the atom engine version constraint in the `package.json` file, I'll fix it and publish tonight.

**Comment by zimme** [comment]
Closed by fb94452ebcede1da68f09c094ba054e782e2830f
